#!/bin/bash

ACTUAL_THEME=$(plasma-apply-colorscheme --list-schemes | grep 'scheme)$' | awk -F' ' '{print $2}')

if [[ $ACTUAL_THEME == "BreezeLight" ]]; then
	RESULT="BreezeDark";
else 
	RESULT="BreezeLight"
fi

plasma-apply-colorscheme $RESULT &> /dev/null
sleep 3
timeout 1 xsettingsd &> /dev/null
